#!/bin/bash

set -eu

touch "${HOME}/.env"
{
	echo CYPRESS_VIDEO=false
	echo CYPRESS_VIEWPORT_WIDTH="1000"
	echo CYPRESS_VIEWPORT_HEIGHT="660"
	echo TEST_BASE_URL="https://${RANCHER_HOST:-}/dashboard"
	echo TEST_USERNAME="${RANCHER_USERNAME:-admin}"
	echo TEST_PASSWORD="${RANCHER_PASSWORD:-password}"
	echo TEST_SKIP_SETUP=true
	echo TEST_SKIP=setup
	echo AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-}"
	echo AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-}"
	echo AZURE_CLIENT_ID="${AZURE_CLIENT_ID:-}"
	echo AZURE_CLIENT_SECRET="${AZURE_CLIENT_SECRET:-}"
	echo AZURE_AKS_SUBSCRIPTION_ID="${AZURE_AKS_SUBSCRIPTION_ID:-}"
	echo GKE_SERVICE_ACCOUNT="${GKE_SERVICE_ACCOUNT:-}"
	echo CUSTOM_NODE_IP="${CUSTOM_NODE_IP:-}"
	echo CUSTOM_NODE_KEY="${CUSTOM_NODE_KEY:-}"
	echo PERCY_TOKEN="${PERCY_TOKEN:-}"
	echo QASE_REPORT="${QASE_REPORT:-false}"
	echo QASE_PROJECT="${QASE_PROJECT:-SANDBOX}"
	echo QASE_AUTOMATION_TOKEN="${QASE_AUTOMATION_TOKEN:-}"
	echo RANCHER_IMAGE_TAG="${RANCHER_IMAGE_TAG:-unknown}"
	echo RANCHER_VERSION="${RANCHER_VERSION:-}"
} >>"${HOME}/.env"
