#!/bin/bash

set -x

export PATH=$PATH:"${WORKSPACE}/bin"

# Get private key from Ansible output or use the generated SSH key
PRIV_KEY="${WORKSPACE}/.ssh/corral_private_key"
if [ -f "${WORKSPACE}/ansible-output.yaml" ]; then
  # Extract private key from Ansible output if available
  PRIV_KEY_CONTENT=$(yq e '.node_private_key' "${WORKSPACE}/ansible-output.yaml" 2>/dev/null || echo "")
  if [ -n "${PRIV_KEY_CONTENT}" ]; then
    echo "${PRIV_KEY_CONTENT}" | base64 -d > "${PRIV_KEY}" 2>/dev/null || echo "${PRIV_KEY_CONTENT}" > "${PRIV_KEY}"
  else
    # Fallback to the SSH key generated by init.sh
    PRIV_KEY="${WORKSPACE}/.ssh/jenkins_ecdsa"
  fi
else
  # Fallback to the SSH key generated by init.sh
  PRIV_KEY="${WORKSPACE}/.ssh/jenkins_ecdsa"
fi

if [ -f "${PRIV_KEY}" ]; then 
  chmod 700 "${PRIV_KEY}"
  chmod 400 "${PRIV_KEY}"
else
  echo "Error: Private key not found at ${PRIV_KEY}"
  exit 1
fi

# Get node IP from Ansible output
if [ -f "${WORKSPACE}/ansible-output.yaml" ]; then
  NODE_EXTERNAL_IP=$(yq e '.node_external_ip' "${WORKSPACE}/ansible-output.yaml" 2>/dev/null || echo "")
  if [ -z "${NODE_EXTERNAL_IP}" ]; then
    # Try alternative field names
    NODE_EXTERNAL_IP=$(yq e '.first_node_ip' "${WORKSPACE}/ansible-output.yaml" 2>/dev/null || echo "")
  fi
else
  # Fallback to environment variable if set by init.sh
  NODE_EXTERNAL_IP="${NODE_EXTERNAL_IP:-}"
fi

if [ -z "${NODE_EXTERNAL_IP}" ]; then
  echo "Error: Node external IP not found. Check ansible-output.yaml or NODE_EXTERNAL_IP environment variable."
  exit 1
fi


REPORT_DIR="."

if [[ $# -gt 1 ]]; then
  REPORT_DIR="$2"
  mkdir -p "$2"
fi

scp -r -i ${PRIV_KEY} -o StrictHostKeyChecking=no \
  -o UserKnownHostsFile=/dev/null "root@${NODE_EXTERNAL_IP}:$1" "${REPORT_DIR}"
